### ISSUE TITLE
BS4 required.. 

### ISSUE THREAD

**Issue by nickknyc** [techleadhd/chatgpt-retrieval#4]
Running windows 11, Python 3.11, in a venv. following docs I got an error on the first run 
"ModuleNotFoundError: No module named 'bs4'"
pip install bs4 in the virtual environment fixed it up.

**Comment by leyncho** [comment]
you need to install beautifulsoup4 so run this in the terminal:

For MacOS: `sudo pip3 install beautifulsoup4`
For Windows: `pip3 install beautifulsoup4`

then run your code again, should work.
